// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AuthStatus():Promise<main.AuthStatusResponse>;

export function ClearJWT():Promise<void>;

export function GetMessages(arg1:string):Promise<string>;

export function OpenLoginInBrowser():Promise<void>;

export function SetJWTManually(arg1:string):Promise<main.AuthStatusResponse>;

export function StartJWTCapture():Promise<main.JWTCaptureSession>;

export function StopJWTCapture():Promise<void>;
