// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuthStatus() {
  return window['go']['main']['App']['AuthStatus']();
}

export function ClearJWT() {
  return window['go']['main']['App']['ClearJWT']();
}

export function GetMessages(arg1) {
  return window['go']['main']['App']['GetMessages'](arg1);
}

export function OpenLoginInBrowser() {
  return window['go']['main']['App']['OpenLoginInBrowser']();
}

export function SetJWTManually(arg1) {
  return window['go']['main']['App']['SetJWTManually'](arg1);
}

export function StartJWTCapture() {
  return window['go']['main']['App']['StartJWTCapture']();
}

export function StopJWTCapture() {
  return window['go']['main']['App']['StopJWTCapture']();
}
